version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www:cached
      - composer_cache:/root/.composer/cache
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: sistema_zayavok
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        if [ ! -f .env ]; then cp .env.example .env || true; fi &&
        composer install --no-interaction --prefer-dist &&
        php artisan key:generate --force &&
        php artisan migrate --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  db:
    image: mysql:8.0
    container_name: sistema-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sistema_zayavok
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      retries: 10
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin:5
    container_name: sistema-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"

volumes:
  db_data:
  composer_cache:
